# Generated by Django 2.2.1 on 2019-06-09 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('nacionalidad', models.CharField(max_length=50)),
                ('creditos', models.IntegerField(default=2)),
                ('premium', models.BooleanField(default=False, verbose_name='premium estatus')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('habitaciones', models.IntegerField(default=0)),
                ('personas', models.IntegerField(default=0)),
                ('baños', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('creditos', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateField()),
                ('precio_reserva', models.DecimalField(decimal_places=2, max_digits=11)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=11)),
                ('inicio_de_subasta', models.DateField()),
                ('iniciada', models.BooleanField(default=False)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='main.Residencia')),
                ('usuarios_inscriptos', models.ManyToManyField(related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_inicial', 'residencia'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemanaReservada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateField()),
                ('precio_reserva', models.DecimalField(decimal_places=2, max_digits=11)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_reservadas', to='main.Residencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_reservadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_inicial', 'residencia'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero_pujado', models.DecimalField(decimal_places=2, max_digits=11)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='main.Subasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subasta', '-dinero_pujado'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='staticfiles/fotos')),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='main.Residencia')),
            ],
        ),
        migrations.CreateModel(
            name='HotSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateField()),
                ('precio_reserva', models.DecimalField(decimal_places=2, max_digits=11)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotsales', to='main.Residencia')),
            ],
            options={
                'ordering': ['dia_inicial', 'residencia'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
