# Generated by Django 2.2.1 on 2019-06-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(default='1999-03-25', verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
