# Generated by Django 2.2.1 on 2019-05-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190504_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('habitaciones', models.IntegerField()),
                ('personas', models.IntegerField()),
                ('baños', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
