# Generated by Django 2.2.1 on 2019-06-10 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190609_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
