# Generated by Django 2.2.1 on 2019-05-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190504_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='baños',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='personas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaInicial', models.DateField()),
                ('diaFinal', models.DateField()),
                ('precioReserva', models.FloatField()),
                ('precioInicial', models.FloatField()),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='main.Residencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaInicial', models.DateField()),
                ('diaFinal', models.DateField()),
                ('precioReserva', models.FloatField()),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotsales', to='main.Residencia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
