# Generated by Django 2.2.1 on 2019-06-10 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190610_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2019, 6, 10), verbose_name='fecha de nacimiento'),
        ),
    ]
