# Generated by Django 2.2.1 on 2019-06-10 19:18

from django.db import migrations
from django.utils import timezone

def actualizar_fechas(apps, schema_editor):
	User = apps.get_model('main', 'User')
	for user in User.objects.all():
		user.date_of_birth = timezone.now()
		user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190610_1610'),
    ]

    operations = [
    	migrations.RunPython(actualizar_fechas),
    ]
