# Generated by Django 2.2.1 on 2019-05-05 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190504_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='inicio_de_subasta',
            field=models.DateField(default=datetime.date(2019, 5, 5)),
        ),
    ]
