# Generated by Django 2.2.1 on 2019-06-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190610_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puja',
            options={'ordering': ['subasta', 'dinero_pujado']},
        ),
    ]
