# Generated by Django 2.2.1 on 2019-06-18 02:52

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190617_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(default='4532661247991100', max_length=25, verbose_name='card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(default='11/19', verbose_name='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(default='374', max_length=4, verbose_name='security code')),
            ],
        ),
    ]
