# Generated by Django 2.2.1 on 2019-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190512_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsale',
            name='dia_inicial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='dia_inicial',
            field=models.DateField(),
        ),
    ]
