# Generated by Django 2.2.1 on 2019-06-18 02:54

from django.db import migrations, models
from main.models import Tarjeta
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metodo_de_pago',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.Tarjeta'),
            preserve_default=False,
        ),
    ]
