# Generated by Django 2.2.1 on 2019-05-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190513_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsale',
            options={'ordering': ['dia_inicial']},
        ),
        migrations.AlterModelOptions(
            name='subasta',
            options={'ordering': ['dia_inicial']},
        ),
    ]
