# Generated by Django 2.2.1 on 2019-05-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190513_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residencia',
            options={'ordering': ['nombre']},
        ),
    ]
