# Generated by Django 2.1.5 on 2019-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_metodo_de_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.DecimalField(decimal_places=2, default=100, max_digits=11, unique=True)),
                ('basico', models.DecimalField(decimal_places=2, default=50, max_digits=11, unique=True)),
            ],
        ),
    ]
