# Generated by Django 2.2.1 on 2019-06-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_suscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name_plural': 'Precios de Suscripciones'},
        ),
    ]
