# Generated by Django 2.2.1 on 2019-05-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190513_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsale',
            options={'ordering': ['dia_inicial', '__str__']},
        ),
        migrations.AlterModelOptions(
            name='subasta',
            options={'ordering': ['dia_inicial', '__str__']},
        ),
    ]
