# Generated by Django 2.2.1 on 2019-05-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190513_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsale',
            options={'ordering': ['dia_inicial', 'residencia']},
        ),
        migrations.AlterModelOptions(
            name='subasta',
            options={'ordering': ['dia_inicial', 'residencia']},
        ),
    ]
