# Generated by Django 2.2.1 on 2019-05-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190513_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='ciudad',
            field=models.CharField(default='Buenos Aires', max_length=100),
            preserve_default=False,
        ),
    ]
