# Generated by Django 2.2.1 on 2019-07-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_semanareservada_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaPasada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateField()),
                ('precio_reserva', models.DecimalField(decimal_places=2, max_digits=11)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_pasadas', to='main.Residencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_pasadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_inicial', 'residencia'],
                'abstract': False,
            },
        ),
    ]
