# Generated by Django 2.2.1 on 2019-05-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_residencia_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='pais',
            field=models.CharField(default='Argentina', max_length=30),
            preserve_default=False,
        ),
    ]
