# Generated by Django 2.2.1 on 2019-07-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_semanapasada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opinion', to='main.SemanaPasada')),
            ],
        ),
    ]
