# Generated by Django 2.2.1 on 2019-05-19 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='subasta',
            name='precio_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.CreateModel(
            name='SubastaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios_inscriptos', models.ManyToManyField(related_name='inscripciones', to='main.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SemanaReservada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicial', models.DateField()),
                ('precio_reserva', models.FloatField()),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_reservadas', to='main.Residencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_reservadas', to='main.Usuario')),
            ],
            options={
                'ordering': ['dia_inicial', 'residencia'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero_pujado', models.DecimalField(decimal_places=2, max_digits=11)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='main.SubastaEvento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='main.Usuario')),
            ],
        ),
    ]
