# Generated by Django 2.2.1 on 2019-05-19 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190519_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='fin_subasta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
