# Generated by Django 2.1.5 on 2019-07-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(default='#!', max_length=200),
        ),
    ]
