# Generated by Django 2.2.1 on 2019-07-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_notificacion_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='semana',
        ),
        migrations.AddField(
            model_name='semanapasada',
            name='opinion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semana', to='main.Opinion'),
        ),
    ]
