# Generated by Django 2.2.1 on 2019-05-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subasta_fin_subasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='fin_subasta',
        ),
    ]
