# Generated by Django 2.2.1 on 2019-07-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190713_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name_plural': 'Automatización y suscripciones'},
        ),
        migrations.AlterField(
            model_name='opinion',
            name='puntaje',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
