# Generated by Django 2.2.1 on 2019-05-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_subasta_fin_subasta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puja',
            options={'ordering': ['subasta', '-dinero_pujado']},
        ),
    ]
