# Generated by Django 2.2.1 on 2019-05-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190519_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsale',
            name='precio_reserva',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='semanareservada',
            name='precio_reserva',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='precio_reserva',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
