# Generated by Django 2.2.1 on 2019-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190521_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='iniciada',
            field=models.BooleanField(default=False),
        ),
    ]
